# Generated by Django 2.0.2 on 2018-07-18 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_candidate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employer',
        ),
    ]
