# Generated by Django 2.0.2 on 2018-07-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_users', '0002_auto_20180717_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CANDIDATE', 'Candidate'), ('EMPLOYER', 'Employer')], default='CANDIDATE', max_length=50),
        ),
    ]
